# Generated by Django 4.2.23 on 2025-10-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('entidad_afectada', models.CharField(max_length=50)),
                ('id_registro_afectado', models.IntegerField(blank=True, null=True)),
                ('tipo_evento', models.CharField(max_length=6)),
                ('usuario_sistema', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CandidatoOpcion',
            fields=[
                ('candidato_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_candidato', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('partido', models.CharField(blank=True, max_length=50, null=True)),
                ('lista', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'candidato_opcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('eleccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_eleccion', models.CharField(max_length=13)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_eleccion', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'eleccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionVotacion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_sesion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sesion_votacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_terminal', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'terminal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id_votante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_qr', models.CharField(max_length=256)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'votante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_eleccion', models.CharField(max_length=13)),
                ('fecha_hora_emision', models.DateTimeField()),
                ('voto_encriptado', models.TextField()),
                ('hash_verificacion', models.CharField(max_length=256)),
                ('comprobante_emision', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'voto',
                'managed': False,
            },
        ),
    ]
