# Generated by Django 5.2.8 on 2025-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='votos_pdf/'),
        ),
    ]
