# Generated by Django 5.1.5 on 2025-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'usuario_sistema',
                'managed': False,
            },
        ),
    ]
